### ISSUE TITLE
[Minor] [Resize] When resizing to narrow browser width, will see a flash of a white rectangle (video attached) (no problem on safari)

### ISSUE THREAD

**Issue by joyzoursky** [oursky/oursky-site#28]
video: https://vid.me/hxyz

**Comment by KitFung** [comment]
I think this issue have been solved by #31 Fix frank

**Comment by chpapa** [comment]
Can @joyzoursky confirm and close this issue if appropriate? Thanks!

**Comment by KitFung** [comment]
Oh, i think i misunderstood the previous commit. 
Can I let the main navigation page having the same effect as it mobile view (opacity effect)
like this: http://gyazo.com/1606c6821b7917ba9cc4d78829df3035

this can solve this issue:http://gyazo.com/85352f674c219b1a3fe0b9b38269a4a6
otherwise, we need to keep check the browser width.
